name: Multi Env Custom Action

on:
  workflow_dispatch:

jobs:
  build-package:
    runs-on: ubuntu-latest
    environment: development

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get environment variables
      uses: Sumit007521/getEnvVars@feature/multiEnv
      with:
        env_name: "production,development,staging"
        gh_token: ${{ secrets.GH_TOKEN }}

    - name: Print Files
      run: ls

    # - name: Upload environment variables
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: env_var
    #     path: |
    #         env_var.json 
    #         env_var.txt
