name: Multi Env Custom Action

on:
  workflow_dispatch:

jobs:
  build-package:
    runs-on: ubuntu-latest
    environment: development

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get environment variables
      uses: Sumit007521/getEnvVars@v1.0.0
      with:
        repo : "Sumit007521/React-Pizza-App"
        env_name: "production,development"
        gh_token: ${{ secrets.GH_TOKEN }}
        file_type: 'csv'

    - name: Print Files
      run: ls

    - name: Upload environment variables
      uses: actions/upload-artifact@v4
      with:
        name: env_var
        path: |
            production.csv
            development.csv
            production..json
